#!/bin/bash
#
# fhg_ifx_onmode_f: free unused SHM
# 
# Copyright (c) 2012 FuH Entwicklungsgesellschaft mbH, Umkirch, Germany. All rights reserved.
# Author: Philipp Hoefflin, 2012, hoefflin@fuh-e.de
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation in version 2.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 675 Mass Ave, Cambridge MA 02139, USA or see <http://www.gnu.org/licenses/>
#
#
TPRO=`basename $0`
TRACEFIL=/tmp/$TPRO.out
CMD="onmode -F"

echo -e "$TPRO: BEGIN\t'$CMD'\t\t`date`"	>$TRACEFIL

su - informix <<EOF
	INFORMIXUMGEBUNG=IDS
	. /usr/local/etc/ifxini || exit 1
	$CMD
EOF
ERR=$?

echo -e "$TPRO: END\t'$CMD' Exit: $ERR\t`date`"	>>$TRACEFIL

exit $ERR
